In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle
import numpy as np

In [2]:
with open('/content/drive/MyDrive/SEM 7/ML - Ops/scaler.pkl','rb') as f:
  scaler = pickle.load(f)

In [3]:
x_test = np.load('/content/drive/MyDrive/SEM 7/ML - Ops/x_test.npy', allow_pickle=True)

In [4]:
x_train_normalized_Main = np.load('/content/drive/MyDrive/SEM 7/ML - Ops/x_train_normalized.npy', allow_pickle=True)
x_test_normalized_Main = np.load('/content/drive/MyDrive/SEM 7/ML - Ops/x_test_normalized.npy' ,allow_pickle=True)

In [5]:
'''Converting pd series to numpy array'''
x_test = np.asarray(x_test).reshape(-1,1)

In [6]:
x_test_normalized = scaler.transform(x_test)

In [7]:
x_test_normalized

array([[ 0.33875048],
       [ 0.61125674],
       [-0.5060189 ],
       [-0.0700089 ],
       [-0.54235307],
       [ 0.7111757 ],
       [ 1.52869446],
       [-0.07455067],
       [-0.86936058],
       [-1.11461621],
       [ 1.55594508],
       [-0.55416168],
       [-0.65135557],
       [-0.93294537],
       [-0.5378113 ],
       [-0.69223151],
       [-1.43254017],
       [ 0.38416819],
       [ 0.31604163],
       [ 0.38416819],
       [-0.06092536],
       [ 0.75886429],
       [-0.68360215],
       [-0.61502141],
       [ 1.40606664],
       [ 2.18270947],
       [-0.93748714],
       [-0.97836308],
       [ 3.65424324],
       [-0.97836308],
       [-0.52418599],
       [-0.92386183],
       [ 0.38416819],
       [ 0.6634871 ],
       [-0.17219874],
       [-0.25167973],
       [-0.23078759],
       [-0.8966112 ],
       [-0.76035808],
       [-1.0751028 ],
       [ 1.28343883],
       [-0.69223151],
       [ 0.57492257],
       [-0.43335057],
       [ 0.72480101],
       [ 0

In [8]:
np.mean(x_test_normalized)

-0.008182479453515227

In [9]:
np.std(x_test_normalized)

0.9210591725069316

In [10]:
x_test

array([[ 5900],
       [ 6500],
       [ 4040],
       [ 5000],
       [ 3960],
       [ 6720],
       [ 8520],
       [ 4990],
       [ 3240],
       [ 2700],
       [ 8580],
       [ 3934],
       [ 3720],
       [ 3100],
       [ 3970],
       [ 3630],
       [ 2000],
       [ 6000],
       [ 5850],
       [ 6000],
       [ 5020],
       [ 6825],
       [ 3649],
       [ 3800],
       [ 8250],
       [ 9960],
       [ 3090],
       [ 3000],
       [13200],
       [ 3000],
       [ 4000],
       [ 3120],
       [ 6000],
       [ 6615],
       [ 4775],
       [ 4600],
       [ 4646],
       [ 3180],
       [ 3480],
       [ 2787],
       [ 7980],
       [ 3630],
       [ 6420],
       [ 4200],
       [ 6750],
       [ 5885],
       [ 6000],
       [ 4640],
       [ 8050],
       [ 3000],
       [ 7475],
       [ 3000],
       [ 7770],
       [ 4500],
       [ 3640],
       [ 2910],
       [ 5750],
       [ 2400],
       [ 6450],
       [ 3800],
       [ 3180],
       [ 2135],
       [

In [11]:
x_test_normalized_Main == x_test_normalized


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [12]:
predictions = np.load('/content/drive/MyDrive/SEM 7/ML - Ops/Predictions.npy', allow_pickle=True)

In [13]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [14]:
y_test = np.load('/content/drive/MyDrive/SEM 7/ML - Ops/y_test.npy', allow_pickle=True)

In [15]:
y_test.shape

(109,)

In [16]:
mae = mean_absolute_error(y_test, predictions)

#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_test, predictions) #default=True
rmse = mean_squared_error(y_test, predictions,squared=False)
print("MAE:",mae)
print("MSE:",mse)
print("RMSE:",rmse)

MAE: 1474748.1337969352
MSE: 3675286604768.1855
RMSE: 1917103.7021424235
